export default {
  safeArea: {
    flex: 1,
    backgroundColor: "#f5f3ff",
  },
  flexOne: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 0,
    paddingBottom: 28,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 0,
    paddingBottom: 10,
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: "#111827",
  },
  subtitle: {
    marginTop: 4,
    color: "#6b7280",
  },
  backButton: {
    padding: 8,
    borderRadius: 10,
    backgroundColor: "#f3f4f6",
  },
  pickerWrap: {
    backgroundColor: "#f9fafb",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    overflow: "hidden",
  },
  createButton: {
    backgroundColor: "#6b21a8",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  createButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  filterCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 14,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  filterLabel: {
    marginBottom: 10,
    fontWeight: "700",
    color: "#374151",
  },
  filterRow: {
    gap: 8,
  },
  centerChip: {
    backgroundColor: "#f3f4f6",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  centerChipActive: {
    backgroundColor: "#ede9fe",
  },
  centerChipText: {
    color: "#4b5563",
    fontWeight: "700",
    fontSize: 12,
  },
  centerChipTextActive: {
    color: "#6d28d9",
  },
  formCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  listCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111827",
  },
  mutedText: {
    color: "#6b7280",
    fontSize: 12,
  },
  fieldGroup: {
    marginBottom: 14,
  },
  rowFields: {
    flexDirection: "row",
    gap: 12,
  },
  flexHalf: {
    flex: 1,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  label: {
    color: "#374151",
    fontWeight: "700",
    fontSize: 13,
  },
  labelError: {
    color: "#dc2626",
  },
  requiredAsterisk: {
    color: "#dc2626",
    fontWeight: "800",
    marginLeft: 2,
  },
  input: {
    backgroundColor: "#f9fafb",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 14,
    color: "#111827",
  },
  inputError: {
    borderColor: "#dc2626",
  },
  dateButton: {
    backgroundColor: "#f9fafb",
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  dateButtonText: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "600",
  },
  dateButtonPlaceholder: {
    color: "#9ca3af",
  },
  dateButtonIcon: {
    fontSize: 16,
  },
  infoBadgeWrap: {
    backgroundColor: "#f5f3ff",
    borderWidth: 1,
    borderColor: "#ddd6fe",
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  infoBadgeText: {
    color: "#6d28d9",
    fontWeight: "800",
  },
  segmentRow: {
    flexDirection: "row",
    backgroundColor: "#f3f4f6",
    borderRadius: 12,
    padding: 4,
    gap: 4,
  },
  segmentButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 9,
    alignItems: "center",
  },
  segmentButtonActive: {
    backgroundColor: "#6d28d9",
  },
  segmentText: {
    color: "#374151",
    fontWeight: "700",
    fontSize: 13,
  },
  segmentTextActive: {
    color: "#fff",
  },
  toggleRow: {
    flexDirection: "row",
    gap: 10,
  },
  toggleButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: "center",
  },
  toggleButtonActive: {
    backgroundColor: "#ede9fe",
    borderColor: "#8b5cf6",
  },
  toggleButtonText: {
    color: "#111827",
    fontWeight: "700",
  },
  toggleButtonTextActive: {
    color: "#6d28d9",
  },
  primaryButton: {
    backgroundColor: "#6d28d9",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 4,
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "800",
  },
  secondaryButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#ede9fe",
  },
  secondaryButtonText: {
    color: "#6d28d9",
    fontWeight: "700",
  },
  loaderWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loaderWrapSmall: {
    paddingVertical: 20,
    alignItems: "center",
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 24,
  },
  emptyStateText: {
    marginTop: 10,
    color: "#6b7280",
    textAlign: "center",
  },
  discountCard: {
    borderWidth: 1,
    borderColor: "#ede9fe",
    borderRadius: 16,
    padding: 14,
    marginBottom: 12,
    backgroundColor: "#faf5ff",
  },
  discountHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  discountTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "800",
  },
  discountMeta: {
    color: "#6b7280",
    marginTop: 3,
    fontSize: 12,
  },
  discountInfo: {
    color: "#4b5563",
    marginTop: 10,
    fontSize: 13,
  },
  expiredText: {
    color: "#dc2626",
    fontWeight: "700",
    marginTop: 8,
    fontSize: 12,
  },
  statusPill: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusPillActive: {
    backgroundColor: "#dcfce7",
  },
  statusPillPaused: {
    backgroundColor: "#f3f4f6",
  },
  statusText: {
    fontSize: 11,
    fontWeight: "800",
  },
  statusTextActive: {
    color: "#15803d",
  },
  statusTextPaused: {
    color: "#374151",
  },
  actionRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  editButton: {
    flex: 1,
    backgroundColor: "#7c3aed",
    borderRadius: 12,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
  },
  deleteButton: {
    flex: 1,
    backgroundColor: "#d11a2a",
    borderRadius: 12,
    paddingVertical: 10,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 6,
  },
  actionText: {
    color: "#fff",
    fontWeight: "700",
  },
};
