import { createTypographyStyleSheet as StyleSheet } from "./theme/typography";
import { colors } from "./theme/colors";
import { spacing } from "./theme/spacing";
import { radius } from "./theme/radius";
import { shadows } from "./theme/shadows";
import { responsive } from "./theme/responsive";
import { typography } from "./theme/typography";

const purple = colors.primary;
const darkPurple = colors.text;
const mutedPurple = colors.textMuted;
const lightPurple = "#F8EEFF";
const lightPink = "#FCE7F3";

export default StyleSheet({
  wrapper: { flex: 1 },
  scrollContent: { paddingBottom: 28 },
  loaderContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  heroBackground: {
    minHeight: 300,
    overflow: "hidden",
    borderBottomLeftRadius: radius.xxl + spacing.sm,
    borderBottomRightRadius: radius.xxl + spacing.sm,
  },
  header: {
    height: 74,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.xxl,
  },
  headerButton: {
    width: 46,
    height: 46,
    alignItems: "center",
    justifyContent: "center",
  },
  logo: { width: 154, height: 64 },
  profileHero: {
    minHeight: 112,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
    paddingRight: spacing.xxxl + spacing.xl,
    position: "relative",
  },
  profileHeroTablet: {
    alignSelf: "center",
    width: "100%",
    maxWidth: responsive.contentMaxWidth,
    paddingHorizontal: spacing.xxxl + spacing.xxxl,
  },
  avatarArea: {
    position: "relative",
    flexShrink: 0,
    marginRight: spacing.lg,
  },
  avatar: {
    width: 80,
    height: 80,
    borderRadius: radius.round,
    borderWidth: 4,
    borderColor: colors.surface,
    backgroundColor: lightPurple,
  },

  profileIdentity: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
    zIndex: 1,
  },
  profileOptionsButton: {
    position: "absolute",
    top: spacing.xxxl,
    right: spacing.lg,
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  verifiedBadge: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs + 2,
    margin: 0,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.round,
    backgroundColor: lightPink,
    borderWidth: 1,
    borderColor: "#F0C8EB",
  },
  verifiedText: {
    color: colors.primaryDark,
    fontSize: 10,
    fontWeight: typography.weights.bold,
  },
  name: {
    fontSize: 15,
    lineHeight: 37,
    fontWeight: typography.weights.bold,
    flexShrink: 1,
  },
  heroPaw: {
    position: "absolute",
    right: 20,
    bottom: 18,
    transform: [{ rotate: "-18deg" }],
  },
  content: {
    width: "100%",
    paddingHorizontal: responsive.horizontalPadding,
  },
  contentTablet: {
    maxWidth: responsive.contentMaxWidth,
    alignSelf: "center",
    paddingHorizontal: spacing.xxxl - spacing.xs,
  },
  infoCard: {
    width: "100%",
    paddingHorizontal: spacing.md + 5,
    paddingVertical: spacing.xs,
    borderRadius: radius.xxl + spacing.xs,
    borderWidth: 1,
    ...shadows.sm,
  },
  infoRow: {
    minHeight: 76,
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.md,
  },
  infoRowDivider: { borderBottomWidth: 1, borderBottomColor: colors.border },
  infoIcon: {
    width: spacing.xl + spacing.xl,
    height: spacing.xl + spacing.xl,
    borderRadius: radius.round,
    alignItems: "center",
    justifyContent: "center",
    marginRight: spacing.md + 2,
  },
  infoCopy: { flex: 1, minWidth: 0 },
  label: {
    fontSize: typography.small,
    lineHeight: 18,
    fontWeight: typography.weights.semibold,
    marginBottom: spacing.xs - 1,
  },
  value: {
    fontSize: 12,
    lineHeight: 22,
    fontWeight: typography.weights.medium,
  },
  documentCard: {
    marginTop: spacing.sm,
    padding: spacing.md + 1,
    borderRadius: radius.xxl + spacing.xs,
    borderWidth: 1,
    ...shadows.sm,
  },
  documentHeader: { flexDirection: "row", alignItems: "center", minHeight: 64 },
  pdfIcon: {
    width: 62,
    height: 62,
    borderRadius: radius.lg + spacing.xs,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: lightPurple,
    marginRight: spacing.md + 2,
  },
  documentCopy: { flex: 1 },
  documentTitle: {
    fontSize: 15,
    lineHeight: 24,
    fontWeight: typography.weights.bold,
  },
  documentSubTitle: {
    fontSize: typography.small + 2,
    lineHeight: 20,
    marginTop: spacing.xs - 1,
  },
  viewDocumentBtn: {
    borderRadius: radius.xxl,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm + 1,
    marginTop: spacing.lg,
  },
  viewDocumentText: {
    color: "#6A1B9A",
    fontSize: 12,
    fontWeight: typography.weights.bold,
  },

  primaryButton: {
    height: spacing.buttonHeight + spacing.sm + 1,
    borderRadius: radius.xxl,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm + 2,
  },
  primaryButtonText: {
    color: colors.surface,
    fontSize: typography.subtitle + 2,
    fontWeight: typography.weights.bold,
  },
  petsCard: {
    minHeight: 78,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md + 1,
    marginTop: spacing.sm,
    borderRadius: radius.xxl + 1,
    borderWidth: 1,
    ...shadows.sm,
  },
  petsIcon: {
    width: 50,
    height: 50,
    borderRadius: radius.round,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: lightPurple,
    marginRight: spacing.md + 2,
  },
  petsTitle: {
    flex: 1,
    fontSize: typography.subtitle + 2,
    fontWeight: typography.weights.bold,
  },

  descriptionText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "bold",
  },
  guestContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 28,
  },
  guestDecor: {
    position: "absolute",
    top: 80,
    right: 20,
    transform: [{ rotate: "20deg" }],
  },
  guestAvatar: {
    width: 118,
    height: 118,
    borderRadius: 59,
    borderWidth: 4,
    borderColor: "#FFFFFF",
    marginBottom: 18,
  },
  guestBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 13,
    paddingVertical: 7,
    borderRadius: 18,
    backgroundColor: "#FCE7F3",
  },
  guestBadgeText: { color: "#7B2CBF", fontSize: 13, fontWeight: "700" },
  guestTitle: {
    color: darkPurple,
    fontSize: typography.screenTitle + spacing.xs - 1,
    fontWeight: typography.weights.bold,
    marginTop: spacing.md + 2,
  },
  guestText: {
    maxWidth: 360,
    color: mutedPurple,
    fontSize: typography.subtitle - 1,
    lineHeight: 22,
    textAlign: "center",
    marginTop: spacing.sm + 1,
  },
  guestButtonWrap: { width: "100%", maxWidth: 360, marginTop: spacing.xxl + 1 },
  guestButton: {
    height: spacing.buttonHeight + spacing.sm,
    borderRadius: radius.xxl - 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm + 1,
  },
  guestButtonText: {
    color: colors.surface,
    fontSize: typography.subtitle,
    fontWeight: typography.weights.bold,
  },
});
