import { StyleSheet } from "react-native";

export default StyleSheet.create({
  loaderContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fdf2f8",
  },
  screen: {
    flex: 1,
    backgroundColor: "#faf5ff",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 12,
    marginBottom: 4,
    backgroundColor: "#fffaf7",
    borderBottomWidth: 1,
    borderBottomColor: "#e9d5ff",
  },
  heading: {
    fontSize: 28,
    fontWeight: "800",
    color: "#6b21a8",
    marginLeft: 2,
  },
  addBtn: {
    backgroundColor: "#6b21a8",
    width: 58,
    height: 58,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#8b5cf6",
    elevation: 4,
    shadowColor: "#6b21a8",
    shadowOpacity: 0.22,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  container: {
    padding: 16,
    paddingBottom: 100,
    backgroundColor: "#f8fafc",
    flexGrow: 1,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255,255,255,0.7)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 20,
  },
  paginationFooter: {
    width: "100%",
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 16,
  },
  nextPageButton: {
    backgroundColor: "#6b21a8",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 999,
    minWidth: 180,
    alignItems: "center",
  },
  nextPageButtonText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "700",
  },
});
