import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 32,
  },
  heroCard: {
    backgroundColor: "rgba(255,255,255,0.8)",
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    shadowColor: "#7c3aed",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  heroBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#ede9fe",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    marginBottom: 10,
  },
  heroBadgeText: {
    color: "#6d28d9",
    fontWeight: "700",
    fontSize: 12,
  },
  centerName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1f2937",
    marginBottom: 6,
  },
  heroSubtitle: {
    fontSize: 14,
    color: "#6b7280",
    lineHeight: 20,
  },
  summaryGrid: {
    flexDirection: "row",
    marginTop: 16,
    gap: 12,
  },
  summaryChip: {
    flex: 1,
    backgroundColor: "#f5f3ff",
    padding: 12,
    borderRadius: 16,
  },
  summaryChipLabel: {
    fontSize: 12,
    color: "#7c3aed",
    fontWeight: "700",
    marginBottom: 2,
  },
  summaryChipValue: {
    fontSize: 16,
    color: "#111827",
    fontWeight: "800",
  },
  card: {
    backgroundColor: "rgba(255,255,255,0.82)",
    borderRadius: 22,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#c084fc",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 16,
    color: "#111827",
    fontWeight: "800",
    marginBottom: 12,
  },
  methodOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#faf5ff",
    borderWidth: 1,
    borderColor: "#e9d5ff",
    borderRadius: 18,
    padding: 14,
    marginBottom: 10,
  },
  methodOptionActive: {
    borderColor: "#7c3aed",
    backgroundColor: "#f3e8ff",
  },
  methodLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  methodIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ffffff",
    marginRight: 12,
  },
  methodName: {
    fontSize: 15,
    color: "#1f2937",
    fontWeight: "700",
  },
  methodDescription: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 3,
  },
  advanceRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  advancePill: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "#f3f4f6",
    marginRight: 8,
    marginBottom: 8,
  },
  advancePillActive: {
    backgroundColor: "#6d28d9",
  },
  advancePillText: {
    color: "#374151",
    fontWeight: "700",
  },
  advancePillTextActive: {
    color: "#ffffff",
  },
  priceCard: {
    gap: 8,
  },
  priceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  priceLabel: {
    color: "#6b7280",
    fontSize: 14,
  },
  priceValue: {
    color: "#111827",
    fontWeight: "700",
    fontSize: 14,
  },
  priceTotal: {
    color: "#111827",
    fontWeight: "800",
    fontSize: 16,
  },
  helperText: {
    marginTop: 14,
    color: "#6b7280",
    fontSize: 12,
    lineHeight: 18,
  },
  buttonRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 18,
  },
  secondaryButton: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 16,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#d1d5db",
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButtonText: {
    color: "#374151",
    fontWeight: "700",
  },
  primaryButton: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 1,
    overflow: "hidden",
  },
  buttonText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 14,
    textAlign: "center",
    paddingVertical: 13,
  },
  loaderContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#f8f5ff",
  },
});
