import { StyleSheet } from "react-native";

const purple = "#6B21A8";
const ink = "#111827";
const muted = "#6B7280";

export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#FDF9FF" },
  wrapper: { flex: 1, backgroundColor: "#FDF9FF" },
  scrollContent: { paddingBottom: 92 },
  loaderContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#FDF9FF",
    padding: 20,
  },
  emptyTitle: { color: ink, fontSize: 16, fontWeight: "700", marginTop: 16 },
  headerLogo: { width: 108, height: 48 },
  headerActions: { flexDirection: "row", gap: 4 },
  headerIcon: {
    width: 38,
    height: 38,
    alignItems: "center",
    justifyContent: "center",
  },
  sliderContainer: {
    position: "relative",
    overflow: "hidden",
    backgroundColor: "#EDEAF5",
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  sliderImageWrapper: { backgroundColor: "#EEEAF7" },
  sliderImage: { width: "100%", height: "100%" },
  floatingBackButton: {
    position: "absolute",
    top: 16,
    left: 14,
    zIndex: 10,
  },
  sliderOverlay: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 95,
  },
  sliderCountBadge: {
    position: "absolute",
    right: 14,
    bottom: 14,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    backgroundColor: "rgba(17,24,39,.65)",
  },
  sliderCountText: { color: "#FFFFFF", fontSize: 12, fontWeight: "700" },
  sliderDots: {
    position: "absolute",
    bottom: 13,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "center",
  },
  sliderDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "rgba(255,255,255,.6)",
    marginHorizontal: 3,
  },
  sliderDotActive: { width: 19, backgroundColor: "#FFFFFF" },
  emptyImage: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F1ECFA",
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  emptyImageText: {
    color: purple,
    fontSize: 13,
    marginTop: 8,
    fontWeight: "600",
  },
  detailsContainer: {
    width: "100%",
    maxWidth: 1160,
    alignSelf: "center",
    padding: 16,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  titleCopy: { flex: 1, paddingRight: 10 },
  title: { color: ink, fontSize: 18, lineHeight: 31, fontWeight: "800" },
  desc: { color: muted, fontSize: 12, lineHeight: 20, marginTop: 0 },
  rating: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 5,
    maxWidth: "42%",
  },
  ratingValue: { color: ink, fontSize: 14, fontWeight: "800", marginLeft: 4 },
  reviewText: { color: muted, fontSize: 12, marginLeft: 3 },
  addressRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 12,
  },
  addressText: {
    flex: 1,
    color: ink,
    fontSize: 13,
    lineHeight: 19,
    marginHorizontal: 8,
  },
  mapLink: { color: purple, fontSize: 12, fontWeight: "800", paddingTop: 2 },
  quickActions: { flexDirection: "row", gap: 8, marginBottom: 13 },
  quickAction: {
    flex: 1,
    minHeight: 62,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 10,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 13,
  },
  quickActionCopy: { flex: 1 },
  quickActionTitle: { color: ink, fontSize: 12, fontWeight: "800" },
  quickActionValue: { color: muted, fontSize: 10, marginTop: 3 },
  card: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 17,
    padding: 15,
    marginBottom: 13,
    shadowColor: "#352050",
    shadowOpacity: 0.06,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  cardTitle: {
    color: ink,
    fontSize: 15,
    lineHeight: 24,
    fontWeight: "800",
    marginBottom: 12,
  },
  sectionHeader: {
    minHeight: 28,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  sectionHeaderTitle: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionTitle: { color: ink, fontSize: 15, lineHeight: 23, fontWeight: "800" },
  priceGrid: { flexDirection: "row", gap: 8 },
  priceColumn: { flex: 1, alignItems: "center", minWidth: 0 },
  petPlaceholder: {
    width: "100%",
    height: 73,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3F8FC",
    borderRadius: 10,
  },
  petEmoji: { fontSize: 42 },
  petName: { color: ink, fontSize: 12, fontWeight: "800", marginTop: 6 },
  price: { color: purple, fontSize: 12, fontWeight: "800", marginTop: 3 },
  featureGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  featureTile: {
    width: "30.5%",
    minHeight: 64,
    alignItems: "center",
    justifyContent: "center",
    padding: 7,
    backgroundColor: "#FAF7FF",
    borderRadius: 11,
  },
  featureLabel: {
    color: ink,
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "700",
    textAlign: "center",
    marginTop: 5,
  },
  detailGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
    marginTop: 13,
    paddingTop: 8,
  },
  detailItem: {
    width: "50%",
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 7,
    paddingRight: 8,
  },
  detailCopy: { flex: 1, marginLeft: 7 },
  detailLabel: { color: ink, fontSize: 12, fontWeight: "700" },
  detailValue: { color: muted, fontSize: 12, lineHeight: 17, marginTop: 2 },
  licenseLink: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingTop: 12,
    marginTop: 7,
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  licenseLinkText: { color: purple, fontSize: 13, fontWeight: "800" },
  contactGrid: { flexDirection: "row" },
  contactColumn: { flex: 1, paddingRight: 10 },
  contactLine: { flexDirection: "row", alignItems: "center", marginBottom: 10 },
  contactLink: { flex: 1, color: purple, fontSize: 12, marginLeft: 8 },
  hoursColumn: {
    width: "38%",
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-start",
    borderLeftWidth: 1,
    borderLeftColor: "#E5E7EB",
    paddingLeft: 12,
  },
  hoursTitle: { color: ink, fontSize: 13, fontWeight: "800" },
  hoursValue: { color: muted, fontSize: 12, lineHeight: 18, marginTop: 2 },
  instructionsText: { color: muted, fontSize: 13, lineHeight: 20 },
  bookingBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 18,
    backgroundColor: "rgba(250,247,255,.96)",
    borderTopWidth: 1,
    borderTopColor: "#E5E7EB",
  },
  primaryBtn: {
    minHeight: 51,
    borderRadius: 13,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  primaryBtnText: { color: "#FFFFFF", fontSize: 17, fontWeight: "800" },
});
